name: artio
description: "AI Art Generation App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  freezed_annotation: ^2.4.4
  go_router: ^14.6.0
  google_mobile_ads: ^6.0.0
  http: ^1.6.0
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  purchases_flutter: ^9.0.0
  riverpod_annotation: ^2.6.1
  sentry_flutter: ^8.12.0
  share_plus: ^12.0.1
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  storage_client: any
  supabase_flutter: ^2.11.0
  url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  fake_async: ^1.3.3
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  go_router_builder: 2.7.2
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.2
  mockito: ^5.4.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - .env.staging
